# netlify.toml

[build]
  command = "npm run build"
  publish = "build"
  # Environment variables (optional)
  # environment = { NODE_VERSION = "16" }

# Redirect all requests to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
